### ISSUE TITLE
Bump npm package to v1.7.0

### ISSUE THREAD

**Issue by kamikazechaser** [ginman86/deluge#7]

**Comment by ginman86** [comment]
Not sure i understand this. It is currently 1.7.0 in npm, as well as in the source control. Let me know if im missing something.

![image](https://user-images.githubusercontent.com/3515076/27652931-b759fcd0-5bfa-11e7-85e4-54efaaa77b76.png)

**Comment by kamikazechaser** [comment]
Hmm, not sure how I got another version. Looks ok though. Thanks and kudos for this great library!
