### ISSUE TITLE
Update NPM version.

### ISSUE THREAD

**Issue by sanchezand** [ginman86/deluge#9]
Installing the module from NPM returns an old version, maybe forgot to publish to npm?

**Comment by ginman86** [comment]
`1.7.0` should be the latest version. Which version are you getting when you run `npm install deluge`? I just ran it clean and am seeing it install `1.7.0` as expected.

**Comment by sanchezand** [comment]
Well looking at the code on this git "getTorrentRecord" is missing in 1.7.0, is this intentional?

**Comment by ginman86** [comment]
You're right, looks like we never released that code. I just cut a release and published it. You should be able to get it from npm now.
